services:
  mongo:
    image: mongo:latest
    container_name: mongo

  nats:
    container_name: nats
    image: nats:2.14.0-alpine3.22
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  user-service:
    container_name: user-service
    build: ./user-service
    ports:
      - "50050:50050"
    environment:
      - PORT=:50050
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mongo

  auth-service:
    container_name: auth-service
    build: ./auth-service
    ports:
      - "${AUTH_GRPC_PORT:-50051}:${AUTH_GRPC_PORT:-50051}"
    depends_on:
      - nats
      - user-service
    env_file:
      - ./auth-service/.env
    environment:
      - USER_GRPC_URL=user-service:50050

  chat-service:
    container_name: chat-service
    build: ./chat-service
    ports:
      - "${CHAT_GRPC_PORT:-50053}:${CHAT_GRPC_PORT:-50053}"
    depends_on:
      - nats
      - mongo
      - user-service
    env_file:
      - ./chat-service/.env
    environment:
      - USER_GRPC_URL=user-service:50050
      - CHAT_MONGO_URI=mongodb://mongo:27017

  content-service:
    container_name: content-service
    build:
      context: ./content-service
      dockerfile: Dockerfile
    ports:
      - "50052:50052"
    environment:
      - GRPC_PORT=50052
      - MONGO_URI=mongodb://mongo:27017
      - DB_NAME=maxat_content_db
      - REDIS_ADDR=redis:6379
      - USER_SERVICE_URL=user-service:50050
      - NATS_URL=nats://nats:4222
    depends_on:
      - mongo
      - nats
      - user-service

  api-gateway:
    container_name: api-gateway
    build: ./api-gateway
    ports:
      - "${API_GATEWAY_PORT:-8080}:${API_GATEWAY_PORT:-8080}"
    env_file:
      - ./api-gateway/.env
    depends_on:
      - auth-service
      - user-service
      - content-service
      - chat-service
